### ISSUE TITLE
Encountered NoClassDefFoundError on Android platform

### ISSUE THREAD

**Issue by sleepym09** [namiml/react-native-nami-sdk#267]
On Android if I run the follow code:
`Nami.configure();`

app will crash and get an error log: 
`Error: Exception in HostObject::get(property:RNNamiCampaignManager): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/namiml/campaign/NamiCampaign;`

Here is some configuration information of my project:
```
react-native nami: ^3.1.12
android gradle: 4.2.2
maven { url "https://www.jitpack.io" }
maven { url "https://packages.namiml.com/NamiSDK/Android/"}
```
I checkd the apk data and ensrure the NamiCampaign class is included.
<img width="1273" alt="image" src="https://github.com/namiml/react-native-nami-sdk/assets/100856001/1f4f1dad-20b6-4c4c-b265-403c26affbfe">

Note that It works find on iOS.

**Comment by namidan** [comment]
In your android/app/build.gradle you will need something like this:

implementation "com.namiml:sdk-android:3.1.16"

(Please check the release notes for the version of the RN SDK and the native Android dependency it uses here: https://github.com/namiml/react-native-nami-sdk/wiki/Nami-SDK-Stable-Releases)

**Comment by sleepym09** [comment]
Hi @namidan, I add the dependencies and encounter another issue.
The android sdk looks like it depends on `exoplayer 2.18.2`, but my project already relies on `exoplayer 2.12`.
Here is the error log of build.
```
#1
Cannot access class 'ControlDispatcher'. Check your module classpath for missing or conflicting dependencies

#2
Type mismatch: inferred type is PlayerConnector.PlayerControlDispatcher but ControlDispatcher! was expected
```
There are some api changes in these two versions.

Can i force the exoplayer version to 2.12.0?, like this: 
`force "'com.google.android.exoplayer:exoplayer:2.12.0'"`

**Comment by namidan** [comment]
@sleepym09 

You can try that. Let me know how it goes.

**Comment by sleepym09** [comment]
I tried force the version by using `force "com.google.android.exoplayer:exoplayer:2.12.0"`, but i got another error
```
Execution failed for AsmClassesTransform: /Users/zx/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar.
         > Record requires ASM8
```
I found the [pom file](https://packages.namiml.com/NamiSDK/Android/com/namiml/sdk-amazon/3.1.16/sdk-amazon-3.1.16.pom) of the nami android sdk, and it shows a dependency on moshi(1.3.0) and exoplayer(2.18.0).

This is the [solution](https://github.com/square/moshi/issues/1463#issuecomment-1284900496) provided by moshi, But my application can't remove the firebase-perf dependency. Do you have any idea with this?
(By the way, force version is not a good idea, Once the nami sdk is upgraded with exoplayer, this can lead to some unknown errors.)

**Comment by namidan** [comment]
@sleepym09 

Send us a note to support@nami.ml
and we can work through a solution.
