### ISSUE TITLE
Entitlements results some time are false

### ISSUE THREAD

**Issue by elmcapp** [namiml/react-native-nami-sdk#53]
checking entitlements in many cases read false if you place the block of code in a componentDidMount or place in a function component.  In order to get it to work right you have to place it in a timeout.   Some times placing it in a timeout is not aways stable. The only way to use without timeout I have to place the code block in a arrow function that is triggered by button. I was hoping to use it by allowing it to run automatically.  Its like the code runs to fast as if we need to get time for the app to access the internet. 

NativeModules.NamiEntitlementManagerBridge.isEntitlementActive("premium_access", (active) => { 
    if (active) {
      // react to entitlement being active
      console.log(active);
  }
}); 

Result equal false

**Comment by acantarero** [comment]
Confirmed that this method is working correctly.  Please check the logs or the Developer console on the Nami Control Center to ensure that your purchase has been made correctly.
