### ISSUE TITLE
Android app crashes

### ISSUE THREAD

**Issue by elmcapp** [namiml/react-native-nami-sdk#83]
On Android if I run the follow code the app crashes:

NativeModules.NamiBridge.configure(configDict);

If I remove this code the app will run. I have setup everything as what is in the setup documations. It works find on iOS but crashes on Android. 

"react": "17.0.1",
 "react-native": "0.64.2",
"react-native-nami-sdk": "^1.2.0",

buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        ndkVersion = "20.1.5948944"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:4.2.1')
         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.0"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
        maven { url("https://nami-android.s3.amazonaws.com/") }
    }
}

**Comment by acantarero** [comment]
this is not an error with the react native bridge
